### ISSUE TITLE
Tools import order

### ISSUE THREAD

**Issue by jknotts** [aqualid/aqualid#39]
I began work on a new compiler (solaris/cc) and added the file tools/cc.py. This caused the following error during a build:

```
ERROR: Traceback (most recent call last):
  File "lib/python2.7/site-packages/aqualid/__init__.py", line 8307, in main
    status = _main(prj_cfg)
  File "lib/python2.7/site-packages/aqualid/__init__.py", line 8277, in _main
    success = prj.Build()
  File "lib/python2.7/site-packages/aqualid/__init__.py", line 8101, in Build
    force_lock=force_lock)
  File "lib/python2.7/site-packages/aqualid/__init__.py", line 6079, in build
    if not nodes_builder.build(tails):
  File "lib/python2.7/site-packages/aqualid/__init__.py", line 5869, in build
    node.initiate()
  File "lib/python2.7/site-packages/aqualid/__init__.py", line 6568, in initiate
    self.builder = self.builder.initiate()
  File "lib/python2.7/site-packages/aqualid/__init__.py", line 6972, in initiate
    builder.__init__(options, *args, **kw)
  File "lib/python2.7/site-packages/aqualid/tools/cpp_common.py", line 633, in __init__
    super(CommonCppArchiver, self).__init__(options)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

If I change the file name so that it comes after cpp_common.py the issue goes away. I think this has to do with the fact that cc.py is doing the following along with the use of imp.load_module().

```
from .cpp_common import  ToolCommonCpp, CommonCppCompiler, CommonCppArchiver, \
    CommonCppLinker, ToolCommonRes, CommonResCompiler
```

So the order the tools are loaded are as follows: \__init__.py, cc.py, cpp_common.py, ... This means cc.py is loaded before cpp_common.py which imports CommonCppArchiver. When it goes to call `super(CommonCppArchiver, self).__init__(options)` it uses the wrong object, possibly the one that was loaded on the call to imp.load_module(), due to the order in which they were loaded.

**Comment by menify** [comment]
Thank you for reporting the interesting issue.
I will investigate this.

**Comment by menify** [comment]
I reproduced this issue and implemented a fix.
The fix has been committed to pep8 branch 6d04288.

**Comment by jknotts** [comment]
I just wanted to make sure that the dot notation will not be an issue:

https://docs.python.org/2/library/imp.html
> imp.find_module(): This function does not handle hierarchical module names (names containing dots). In order to find P.M, that is, submodule M of package P, use find_module() and load_module() to find and load package P, and then use find_module() with the path argument set to P.__path__. When P itself has a dotted name, apply this recipe recursively.

**Comment by menify** [comment]
Aqualid creates unique package for all tool's directories.
Even if names of tool's modules are identical (/some/dir/gcc.py and /other/dir/gcc.py) they will be loaded as different tools with own name spaces.
Relative dot notation should work fine. I.e. from a tool's module you should be able to use:
```
from .common_lib import foo_bar
from .common_lib.foo import do_action1
from .common_lib.bar.buz import do_action2
```

**Comment by menify** [comment]
Fixed in master
