### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by velkyel** [aqualid/aqualid#49]
according wiki install is done using > python setup.py install  --user but there is no setup.py; what is the actual way how to install?

**Comment by menify** [comment]
setup.py is automatically generated by make.aql bulid script.
Aqualid itself is used to generate setup.py
The simplest way to generate it is using run_ci.py script (which is called by Travis-CI and AppVeyor):

> /run_ci.py -r dist

But it's better to use PyPi:

> pip install aqualid
